language: python
python:
- '2.7'
before_install:
  npm install -g npm@'>=2.13.5'
install:
- pip install flake8 twine
- python setup.py develop
after_script:
- flake8 .
script: python test.py
notifications:
  irc:
    channels:
    - irc.mozilla.org#payments
    on_success: change
    on_failure: always
deploy:
  - provider: pypi
    user: andymckay
    on:
      tags: true
    password:
      secure: VpZdCX4d81ORxXatTx1GTe3LBjb+U2qkbybeQnfx2rnIlUw8DOvmfP9mln6mhaTwHs0g8L92ANvQcw0S3RX7djIw7dffoKVgUVNPty2NZZh6rfGXjRLWMpmte9/CFc5y2atVCrJRwfz7i4JA1O6h1FgGine6/7lv1qEbKN/PRMUuoW4hg27vefugJPnnyuaCGU90Xj4/45B2D9axHB9nhyPa/z73Ma0s5LkiAQtoLczo3VHhXsHh0n0LgNfG6csZeUZZlpMFlOpfwo0JGom/B0tNanzTMCZuCTQdbXftfwNIc6zJ2XtiDLm8BP/aO8iNZKa6TeXrmEH4jgcpGk1C0qIWU4rnOceZlf28djLehFn3acqo8v7GVEgXFCKlaI16nHVu/aj3/PGI7ME6CyWKdiGfsAAPh+39NYxrB9yyaD1hej1SeSyvKr/SJdi74OsRwdB8TD1MZL5OWCfkYGputFlgzAXmWR0E0GfpPr8KpYhXFZimLMtRZhoq5bNfxlXsFtafLnHGT/6CByh1wWIMy+fc0+CsCxTVNjf3qNf3LnvHF+hBhj6UXoYrsGhv+MoTJOp6qSY5jUcOS1rxxJNVvMPealHyUPzrFW9ponRmlM3qLnE94Pa5zqdZBufcbwG2zqrKFxyd5Ca7nKZhUK5ezqbQYou41DAxJTzdepvQxzM=
  - provider: npm
    email: payments-devs-automation+npm@mozilla.com
    on:
      tags: true
      repo: mozilla/payments-config
    api_key:
      secure: jbkrKDUTbAcNGhqWgICh3+wmn6lRVTwH+PsKDKsBHXYda1uECTh8DtzMZD7im4YW0GTWXint4xQX4U3nh7bIj1KvyCQ1XiPhih4ym17iQN0drHw1IgzkXxb67QICriL4pLW3ZoV10AardLFRl6pSM0+W+071njmn5m7u4w/qyX/fDW89DpRzROYajzXEaDM38tAUGLkPGVWI4thamvamBMvBxdTI+DK3zUGiS/Pg5NpvvwqgetlOIKlq+0d7U3YFblrQRVuQV6udXXPm+gpj35htFug9DQmByKjeUe62q54rH9+UPWchJ1tVY0pdYnJKDLmWQCzebc2/c9Zc2jHtR5RI2AKET6DucAHW4UkkqgGGp0+CGk79VDSlWuVSX2ArUmkSM28aqiTbovqMisLBtMGWFhpWTd4oiU68kDNCVuAe6b75in0bDLZDwM80VAiE2wZulij/8xsjvFhpQ90X93M7pMxmj7BcIuCw+qMirnnDTz50+PB9/6vnANcdhG+6CTPSriKylMYsHp0FxHL6YPecg8rfVJSaZuDiOnhFwo67EG79YAtOeGH1wci7Z17YviC+z+1JpEjYmdlKIbMtfrrrY3/uIh5V+2xmK3B/JsJsT/DS5ebbuBAUPsUTRHeWzcpBBhG1QqbLc1Dgb5zypWKpFasQ6lo/CtoXGM410jk=
