language: python
python:
- '2.7'
install:
- pip install flake8
- python setup.py develop
after_script:
- flake8 .
script: python test.py
notifications:
  irc:
    channels:
    - irc.mozilla.org#payments
    on_success: change
    on_failure: always
deploy:
  - provider: pypi
    user: andymckay
    on:
      tags: true
    password:
      secure: VpZdCX4d81ORxXatTx1GTe3LBjb+U2qkbybeQnfx2rnIlUw8DOvmfP9mln6mhaTwHs0g8L92ANvQcw0S3RX7djIw7dffoKVgUVNPty2NZZh6rfGXjRLWMpmte9/CFc5y2atVCrJRwfz7i4JA1O6h1FgGine6/7lv1qEbKN/PRMUuoW4hg27vefugJPnnyuaCGU90Xj4/45B2D9axHB9nhyPa/z73Ma0s5LkiAQtoLczo3VHhXsHh0n0LgNfG6csZeUZZlpMFlOpfwo0JGom/B0tNanzTMCZuCTQdbXftfwNIc6zJ2XtiDLm8BP/aO8iNZKa6TeXrmEH4jgcpGk1C0qIWU4rnOceZlf28djLehFn3acqo8v7GVEgXFCKlaI16nHVu/aj3/PGI7ME6CyWKdiGfsAAPh+39NYxrB9yyaD1hej1SeSyvKr/SJdi74OsRwdB8TD1MZL5OWCfkYGputFlgzAXmWR0E0GfpPr8KpYhXFZimLMtRZhoq5bNfxlXsFtafLnHGT/6CByh1wWIMy+fc0+CsCxTVNjf3qNf3LnvHF+hBhj6UXoYrsGhv+MoTJOp6qSY5jUcOS1rxxJNVvMPealHyUPzrFW9ponRmlM3qLnE94Pa5zqdZBufcbwG2zqrKFxyd5Ca7nKZhUK5ezqbQYou41DAxJTzdepvQxzM=
  - provider: npm
    email: payments-devs-automation+npm@mozilla.com
    on:
      tags: true
      repo: mozilla/payments-config
    api_key:
      secure: c5onC/ZB0K0ratVVxrAwN4So9tbTNmKRICMh0Eh1G4gWztCGouT7f56G4+fAA3ZLFq2fw8BlAGG1lQaI2Pz5y9az1sTeUuxwaJ6301/1NGR+O0D7mptXu2/FZ7Mqiip5ZhlVMjYfMeJfwhuZhl4zdOnm1wqNfPDVJUtAIOaf9yRoxRCodDYXoEeI7zYgVbC+YNlk7llGQZ8BD2fFYu3BdgCUp0HmqRAfUyvQOUm1Uq4wwSxkemcDt9wah4fCjzIdYJaGdviohwYGL/xD8FE8eXCfwAsrREbXPgNGURNOY4brcn2AwcwQDPhvIhqGVAjj0GjnIec7Ym3NcD0lizhXpiBti5mqpxHb1HYtJycU0Xblx/JLX2bXY4biE52NgchHRJKVHUj7LoW1+AW4XTOp4hJP8pyBqj+mheTJUKr6ctY0ulDvEu6tsBxni3zRODWw/hH6kkTU6EH5HJ9KZWEzYinetAw0rc8GS+RVnDWZAwxO45ui/zrL/h/TH4wJhPGuXdvwHx10yPE360J14TqhTlJt5HNKGwemgdqCVzh3NcfhY4GpIVIBxHbF5hdSIdKWjS3Jwg0840cwQ1q1B9YMM0MLA7IszA9Sw/G7hFFpL8pcZwPuMmdxQrK1yYOUXbFcoZe5iISbiRwqTMV1OKqATlYH5fHFw9i0fEIyOOikDEE=
